language: java

jdk:
  - oraclejdk8

before_install:
  - chmod +x ./mvnw

install:
  - ./mvnw clean package -Dmaven.test.skip=true

script:
  - true

deploy:
  provider: azure_web_apps
  skip_cleanup: true
