#Configure Database
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    #hibernate:
      #ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/MahasiswaMS
    username: mahasiswa
    password: mahasiswa
    driverClassName: org.postgresql.Driver

# HTTP Server (Tomcat) Port
server: 
  port: 2002
